name: politikea
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.8
  - pip=24.3.1
  - jupyter=1.0.0
#  - jupyter-core=5.7.2
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - huggingface_hub=0.24.6
  - pip:
    - opencv-python==4.11.0.86